
import { Provincia } from './types';

export const PROVINCE_CYCLE: Provincia[] = [
  Provincia.Firenze,
  Provincia.Siena,
  Provincia.Pisa,
  Provincia.Arezzo,
  Provincia.Lucca,
  Provincia.Grosseto,
  Provincia.Livorno,
  Provincia.Pistoia,
  Provincia.MassaCarrara,
  Provincia.Prato,
];

export const COMUNI_PER_PROVINCIA: Record<Provincia, { nome: string; sigla: string }[]> = {
  [Provincia.Arezzo]: [
    { nome: 'Anghiari', sigla: 'AR' },
    { nome: 'Arezzo', sigla: 'AR' },
    { nome: 'Badia Tedalda', sigla: 'AR' },
    { nome: 'Bibbiena', sigla: 'AR' },
    { nome: 'Bucine', sigla: 'AR' },
    { nome: 'Capolona', sigla: 'AR' },
    { nome: 'Caprese Michelangelo', sigla: 'AR' },
    { nome: 'Castel Focognano', sigla: 'AR' },
    { nome: 'Castel San Niccolò', sigla: 'AR' },
    { nome: 'Castelfranco Piandiscò', sigla: 'AR' },
    { nome: 'Castiglion Fibocchi', sigla: 'AR' },
    { nome: 'Castiglion Fiorentino', sigla: 'AR' },
    { nome: 'Cavriglia', sigla: 'AR' },
    { nome: 'Chitignano', sigla: 'AR' },
    { nome: 'Chiusi della Verna', sigla: 'AR' },
    { nome: 'Civitella in Val di Chiana', sigla: 'AR' },
    { nome: 'Cortona', sigla: 'AR' },
    { nome: 'Foiano della Chiana', sigla: 'AR' },
    { nome: 'Laterina Pergine Valdarno', sigla: 'AR' },
    { nome: 'Loro Ciuffenna', sigla: 'AR' },
    { nome: 'Lucignano', sigla: 'AR' },
    { nome: 'Marciano della Chiana', sigla: 'AR' },
    { nome: 'Monte San Savino', sigla: 'AR' },
    { nome: 'Montemignaio', sigla: 'AR' },
    { nome: 'Monterchi', sigla: 'AR' },
    { nome: 'Montevarchi', sigla: 'AR' },
    { nome: 'Ortignano Raggiolo', sigla: 'AR' },
    { nome: 'Pieve Santo Stefano', sigla: 'AR' },
    { nome: 'Poppi', sigla: 'AR' },
    { nome: 'Pratovecchio Stia', sigla: 'AR' },
    { nome: 'San Giovanni Valdarno', sigla: 'AR' },
    { nome: 'Sansepolcro', sigla: 'AR' },
    { nome: 'Sestino', sigla: 'AR' },
    { nome: 'Subbiano', sigla: 'AR' },
    { nome: 'Talla', sigla: 'AR' },
    { nome: 'Terranuova Bracciolini', sigla: 'AR' },
  ],
  [Provincia.Firenze]: [
    { nome: 'Bagno a Ripoli', sigla: 'FI' },
    { nome: 'Barberino di Mugello', sigla: 'FI' },
    { nome: 'Barberino Tavarnelle', sigla: 'FI' },
    { nome: 'Borgo San Lorenzo', sigla: 'FI' },
    { nome: 'Calenzano', sigla: 'FI' },
    { nome: 'Campi Bisenzio', sigla: 'FI' },
    { nome: 'Capraia e Limite', sigla: 'FI' },
    { nome: 'Castelfiorentino', sigla: 'FI' },
    { nome: 'Cerreto Guidi', sigla: 'FI' },
    { nome: 'Certaldo', sigla: 'FI' },
    { nome: 'Dicomano', sigla: 'FI' },
    { nome: 'Empoli', sigla: 'FI' },
    { nome: 'Fiesole', sigla: 'FI' },
    { nome: 'Figline e Incisa Valdarno', sigla: 'FI' },
    { nome: 'Firenze', sigla: 'FI' },
    { nome: 'Firenzuola', sigla: 'FI' },
    { nome: 'Fucecchio', sigla: 'FI' },
    { nome: 'Gambassi Terme', sigla: 'FI' },
    { nome: 'Greve in Chianti', sigla: 'FI' },
    { nome: 'Impruneta', sigla: 'FI' },
    { nome: 'Lastra a Signa', sigla: 'FI' },
    { nome: 'Londa', sigla: 'FI' },
    { nome: 'Marradi', sigla: 'FI' },
    { nome: 'Montaione', sigla: 'FI' },
    { nome: 'Montelupo Fiorentino', sigla: 'FI' },
    { nome: 'Montespertoli', sigla: 'FI' },
    { nome: 'Palazzuolo sul Senio', sigla: 'FI' },
    { nome: 'Pelago', sigla: 'FI' },
    { nome: 'Pontassieve', sigla: 'FI' },
    { nome: 'Reggello', sigla: 'FI' },
    { nome: 'Rignano sull\'Arno', sigla: 'FI' },
    { nome: 'Rufina', sigla: 'FI' },
    { nome: 'San Casciano in Val di Pesa', sigla: 'FI' },
    { nome: 'San Godenzo', sigla: 'FI' },
    { nome: 'Scandicci', sigla: 'FI' },
    { nome: 'Scarperia e San Piero', sigla: 'FI' },
    { nome: 'Sesto Fiorentino', sigla: 'FI' },
    { nome: 'Signa', sigla: 'FI' },
    { nome: 'Vaglia', sigla: 'FI' },
    { nome: 'Vicchio', sigla: 'FI' },
    { nome: 'Vinci', sigla: 'FI' },
  ],
  [Provincia.Grosseto]: [
    { nome: 'Arcidosso', sigla: 'GR' },
    { nome: 'Campagnatico', sigla: 'GR' },
    { nome: 'Capalbio', sigla: 'GR' },
    { nome: 'Castel del Piano', sigla: 'GR' },
    { nome: 'Castell\'Azzara', sigla: 'GR' },
    { nome: 'Castiglione della Pescaia', sigla: 'GR' },
    { nome: 'Cinigiano', sigla: 'GR' },
    { nome: 'Civitella Paganico', sigla: 'GR' },
    { nome: 'Follonica', sigla: 'GR' },
    { nome: 'Gavorrano', sigla: 'GR' },
    { nome: 'Grosseto', sigla: 'GR' },
    { nome: 'Isola del Giglio', sigla: 'GR' },
    { nome: 'Magliano in Toscana', sigla: 'GR' },
    { nome: 'Manciano', sigla: 'GR' },
    { nome: 'Massa Marittima', sigla: 'GR' },
    { nome: 'Monte Argentario', sigla: 'GR' },
    { nome: 'Monterotondo Marittimo', sigla: 'GR' },
    { nome: 'Montieri', sigla: 'GR' },
    { nome: 'Orbetello', sigla: 'GR' },
    { nome: 'Pitigliano', sigla: 'GR' },
    { nome: 'Roccalbegna', sigla: 'GR' },
    { nome: 'Roccastrada', sigla: 'GR' },
    { nome: 'Santa Fiora', sigla: 'GR' },
    { nome: 'Scansano', sigla: 'GR' },
    { nome: 'Scarlino', sigla: 'GR' },
    { nome: 'Seggiano', sigla: 'GR' },
    { nome: 'Semproniano', sigla: 'GR' },
    { nome: 'Sorano', sigla: 'GR' },
  ],
  [Provincia.Livorno]: [
    { nome: 'Bibbona', sigla: 'LI' },
    { nome: 'Campiglia Marittima', sigla: 'LI' },
    { nome: 'Campo nell\'Elba', sigla: 'LI' },
    { nome: 'Capoliveri', sigla: 'LI' },
    { nome: 'Capraia Isola', sigla: 'LI' },
    { nome: 'Castagneto Carducci', sigla: 'LI' },
    { nome: 'Cecina', sigla: 'LI' },
    { nome: 'Collesalvetti', sigla: 'LI' },
    { nome: 'Livorno', sigla: 'LI' },
    { nome: 'Marciana', sigla: 'LI' },
    { nome: 'Marciana Marina', sigla: 'LI' },
    { nome: 'Piombino', sigla: 'LI' },
    { nome: 'Porto Azzurro', sigla: 'LI' },
    { nome: 'Portoferraio', sigla: 'LI' },
    { nome: 'Rio', sigla: 'LI' },
    { nome: 'Rosignano Marittimo', sigla: 'LI' },
    { nome: 'San Vincenzo', sigla: 'LI' },
    { nome: 'Sassetta', sigla: 'LI' },
    { nome: 'Suvereto', sigla: 'LI' },
  ],
  [Provincia.Lucca]: [
    { nome: 'Altopascio', sigla: 'LU' },
    { nome: 'Bagni di Lucca', sigla: 'LU' },
    { nome: 'Barga', sigla: 'LU' },
    { nome: 'Borgo a Mozzano', sigla: 'LU' },
    { nome: 'Camaiore', sigla: 'LU' },
    { nome: 'Camporgiano', sigla: 'LU' },
    { nome: 'Capannori', sigla: 'LU' },
    { nome: 'Careggine', sigla: 'LU' },
    { nome: 'Castelnuovo di Garfagnana', sigla: 'LU' },
    { nome: 'Castiglione di Garfagnana', sigla: 'LU' },
    { nome: 'Coreglia Antelminelli', sigla: 'LU' },
    { nome: 'Fabbriche di Vergemoli', sigla: 'LU' },
    { nome: 'Forte dei Marmi', sigla: 'LU' },
    { nome: 'Fosciandora', sigla: 'LU' },
    { nome: 'Gallicano', sigla: 'LU' },
    { nome: 'Lucca', sigla: 'LU' },
    { nome: 'Massarosa', sigla: 'LU' },
    { nome: 'Minucciano', sigla: 'LU' },
    { nome: 'Molazzana', sigla: 'LU' },
    { nome: 'Montecarlo', sigla: 'LU' },
    { nome: 'Pescaglia', sigla: 'LU' },
    { nome: 'Piazza al Serchio', sigla: 'LU' },
    { nome: 'Pietrasanta', sigla: 'LU' },
    { nome: 'Pieve Fosciana', sigla: 'LU' },
    { nome: 'Porcari', sigla: 'LU' },
    { nome: 'San Romano in Garfagnana', sigla: 'LU' },
    { nome: 'Seravezza', sigla: 'LU' },
    { nome: 'Sillano Giuncugnano', sigla: 'LU' },
    { nome: 'Stazzema', sigla: 'LU' },
    { nome: 'Vagli Sotto', sigla: 'LU' },
    { nome: 'Viareggio', sigla: 'LU' },
    { nome: 'Villa Basilica', sigla: 'LU' },
    { nome: 'Villa Collemandina', sigla: 'LU' },
  ],
  [Provincia.MassaCarrara]: [
    { nome: 'Aulla', sigla: 'MS' },
    { nome: 'Bagnone', sigla: 'MS' },
    { nome: 'Carrara', sigla: 'MS' },
    { nome: 'Casola in Lunigiana', sigla: 'MS' },
    { nome: 'Comano', sigla: 'MS' },
    { nome: 'Filattiera', sigla: 'MS' },
    { nome: 'Fivizzano', sigla: 'MS' },
    { nome: 'Fosdinovo', sigla: 'MS' },
    { nome: 'Licciana Nardi', sigla: 'MS' },
    { nome: 'Massa', sigla: 'MS' },
    { nome: 'Montignoso', sigla: 'MS' },
    { nome: 'Mulazzo', sigla: 'MS' },
    { nome: 'Podenzana', sigla: 'MS' },
    { nome: 'Pontremoli', sigla: 'MS' },
    { nome: 'Tresana', sigla: 'MS' },
    { nome: 'Villafranca in Lunigiana', sigla: 'MS' },
    { nome: 'Zeri', sigla: 'MS' },
  ],
  [Provincia.Pisa]: [
    { nome: 'Bientina', sigla: 'PI' },
    { nome: 'Buti', sigla: 'PI' },
    { nome: 'Calci', sigla: 'PI' },
    { nome: 'Calcinaia', sigla: 'PI' },
    { nome: 'Capannoli', sigla: 'PI' },
    { nome: 'Casale Marittimo', sigla: 'PI' },
    { nome: 'Casciana Terme Lari', sigla: 'PI' },
    { nome: 'Cascina', sigla: 'PI' },
    { nome: 'Castelfranco di Sotto', sigla: 'PI' },
    { nome: 'Castellina Marittima', sigla: 'PI' },
    { nome: 'Castelnuovo di Val di Cecina', sigla: 'PI' },
    { nome: 'Chianni', sigla: 'PI' },
    { nome: 'Crespina Lorenzana', sigla: 'PI' },
    { nome: 'Fauglia', sigla: 'PI' },
    { nome: 'Guardistallo', sigla: 'PI' },
    { nome: 'Lajatico', sigla: 'PI' },
    { nome: 'Montecatini Val di Cecina', sigla: 'PI' },
    { nome: 'Montescudaio', sigla: 'PI' },
    { nome: 'Monteverdi Marittimo', sigla: 'PI' },
    { nome: 'Montopoli in Val d\'Arno', sigla: 'PI' },
    { nome: 'Orciano Pisano', sigla: 'PI' },
    { nome: 'Palaia', sigla: 'PI' },
    { nome: 'Peccioli', sigla: 'PI' },
    { nome: 'Pisa', sigla: 'PI' },
    { nome: 'Pomarance', sigla: 'PI' },
    { nome: 'Ponsacco', sigla: 'PI' },
    { nome: 'Pontedera', sigla: 'PI' },
    { nome: 'Riparbella', sigla: 'PI' },
    { nome: 'San Giuliano Terme', sigla: 'PI' },
    { nome: 'San Miniato', sigla: 'PI' },
    { nome: 'Santa Croce sull\'Arno', sigla: 'PI' },
    { nome: 'Santa Luce', sigla: 'PI' },
    { nome: 'Santa Maria a Monte', sigla: 'PI' },
    { nome: 'Terricciola', sigla: 'PI' },
    { nome: 'Vecchiano', sigla: 'PI' },
    { nome: 'Vicopisano', sigla: 'PI' },
    { nome: 'Volterra', sigla: 'PI' },
  ],
  [Provincia.Pistoia]: [
    { nome: 'Abetone Cutigliano', sigla: 'PT' },
    { nome: 'Agliana', sigla: 'PT' },
    { nome: 'Buggiano', sigla: 'PT' },
    { nome: 'Chiesina Uzzanese', sigla: 'PT' },
    { nome: 'Lamporecchio', sigla: 'PT' },
    { nome: 'Larciano', sigla: 'PT' },
    { nome: 'Marliana', sigla: 'PT' },
    { nome: 'Massa e Cozzile', sigla: 'PT' },
    { nome: 'Monsummano Terme', sigla: 'PT' },
    { nome: 'Montale', sigla: 'PT' },
    { nome: 'Montecatini Terme', sigla: 'PT' },
    { nome: 'Pescia', sigla: 'PT' },
    { nome: 'Pieve a Nievole', sigla: 'PT' },
    { nome: 'Pistoia', sigla: 'PT' },
    { nome: 'Ponte Buggianese', sigla: 'PT' },
    { nome: 'Quarrata', sigla: 'PT' },
    { nome: 'Sambuca Pistoiese', sigla: 'PT' },
    { nome: 'San Marcello Piteglio', sigla: 'PT' },
    { nome: 'Serravalle Pistoiese', sigla: 'PT' },
    { nome: 'Uzzano', sigla: 'PT' },
  ],
  [Provincia.Prato]: [
    { nome: 'Cantagallo', sigla: 'PO' },
    { nome: 'Carmignano', sigla: 'PO' },
    { nome: 'Montemurlo', sigla: 'PO' },
    { nome: 'Poggio a Caiano', sigla: 'PO' },
    { nome: 'Prato', sigla: 'PO' },
    { nome: 'Vaiano', sigla: 'PO' },
    { nome: 'Vernio', sigla: 'PO' },
  ],
  [Provincia.Siena]: [
    { nome: 'Abbadia San Salvatore', sigla: 'SI' },
    { nome: 'Asciano', sigla: 'SI' },
    { nome: 'Buonconvento', sigla: 'SI' },
    { nome: 'Casole d\'Elsa', sigla: 'SI' },
    { nome: 'Castellina in Chianti', sigla: 'SI' },
    { nome: 'Castelnuovo Berardenga', sigla: 'SI' },
    { nome: 'Castiglione d\'Orcia', sigla: 'SI' },
    { nome: 'Cetona', sigla: 'SI' },
    { nome: 'Chianciano Terme', sigla: 'SI' },
    { nome: 'Chiusdino', sigla: 'SI' },
    { nome: 'Chiusi', sigla: 'SI' },
    { nome: 'Colle di Val d\'Elsa', sigla: 'SI' },
    { nome: 'Gaiole in Chianti', sigla: 'SI' },
    { nome: 'Montalcino', sigla: 'SI' },
    { nome: 'Montepulciano', sigla: 'SI' },
    { nome: 'Monteriggioni', sigla: 'SI' },
    { nome: 'Monteroni d\'Arbia', sigla: 'SI' },
    { nome: 'Monticiano', sigla: 'SI' },
    { nome: 'Murlo', sigla: 'SI' },
    { nome: 'Piancastagnaio', sigla: 'SI' },
    { nome: 'Pienza', sigla: 'SI' },
    { nome: 'Poggibonsi', sigla: 'SI' },
    { nome: 'Radda in Chianti', sigla: 'SI' },
    { nome: 'Radicofani', sigla: 'SI' },
    { nome: 'Radicondoli', sigla: 'SI' },
    { nome: 'Rapolano Terme', sigla: 'SI' },
    { nome: 'San Casciano dei Bagni', sigla: 'SI' },
    { nome: 'San Gimignano', sigla: 'SI' },
    { nome: 'San Quirico d\'Orcia', sigla: 'SI' },
    { nome: 'Sarteano', sigla: 'SI' },
    { nome: 'Siena', sigla: 'SI' },
    { nome: 'Sinalunga', sigla: 'SI' },
    { nome: 'Sovicille', sigla: 'SI' },
    { nome: 'Torrita di Siena', sigla: 'SI' },
    { nome: 'Trequanda', sigla: 'SI' },
  ],
};

export const PROVINCE_COLORS: Record<Provincia, { bg: string, text: string }> = {
    [Provincia.Firenze]: { bg: 'bg-red-100', text: 'text-red-800' },
    [Provincia.Siena]: { bg: 'bg-yellow-100', text: 'text-yellow-800' },
    [Provincia.Pisa]: { bg: 'bg-blue-100', text: 'text-blue-800' },
    [Provincia.Arezzo]: { bg: 'bg-orange-100', text: 'text-orange-800' },
    [Provincia.Lucca]: { bg: 'bg-green-100', text: 'text-green-800' },
    [Provincia.Grosseto]: { bg: 'bg-amber-100', text: 'text-amber-800' },
    [Provincia.Livorno]: { bg: 'bg-sky-100', text: 'text-sky-800' },
    [Provincia.Pistoia]: { bg: 'bg-teal-100', text: 'text-teal-800' },
    [Provincia.MassaCarrara]: { bg: 'bg-gray-200', text: 'text-gray-800' },
    [Provincia.Prato]: { bg: 'bg-indigo-100', text: 'text-indigo-800' },
};
